version: "2"
run:
  go: "1.24"
  modules-download-mode: readonly
output:
  formats:
    code-climate:
      path: stdout
linters:
  disable:
    - depguard
    - exhaustruct
    - ireturn
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
  settings:
    funlen:
      lines: 100
    gocyclo:
      min-complexity: 5
    gosec:
      excludes:
        - G204
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
    varnamelen:
      ignore-names:
        - id
      ignore-decls:
        - ok bool
    wrapcheck:
      ignore-package-globs:
        - google.golang.org/grpc/status
        - github.com/pkg/errors
        - golang.org/x/sync/errgroup
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - containedctx
          - cyclop
          - dupl
          - err113
          - funlen
          - gocyclo
          - govet
          - lll
          - maintidx
          - paralleltest
          - staticcheck
          - varnamelen
          - wsl
        path: _test\.go
      - linters:
          - funlen
          - gochecknoglobals
          - lll
        path: main\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/wissance/Ferrum)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
