{
 "title": "Ferrum WebAPI Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Ferrum WebAPI request duration, ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ferrum_http_request_durations", "legendFormat": "__auto" },
    {
     "expr": "avg(ferrum_http_request_durations)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RAM usage, Mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"10.50.40.3:8182\"} / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(ferrum_http_requests_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage, %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{\"instance\"=\"10.50.40.3:8182\"}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ferrum WebAPI Http  Requests",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ferrum_data_source_requests_total{instance=\"10.50.40.3:8182\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ferrum WebAPI Http Requests Errors",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ferrum_http_requests_error_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"10.50.40.3:8182\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data source Requests durations, us",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{\"ferrum data_source_request_durations\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}