global:
  scrape_interval: 15s # Set the default scrape interval to 15 seconds.

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: ferrum_community_authorization_server
    static_configs:
      - targets: ["10.50.40.3:8182"]