package bruteforce

import (
	"context"
	"github.com/google/uuid"
	"github.com/wissance/Ferrum/errors"
	"sync"
	"time"
)

const blockThreshold = 100
const watchThreshold = blockThreshold / 2
const minTimeToCheck = 30

type attackerList struct {
	mutex                *sync.RWMutex
	ctx                  context.Context
	attackersIPAddresses map[string]uuid.UUID
	attackersDevices     map[string]uuid.UUID
	attackersStats       map[uuid.UUID]AttackerStats
	blockTime            int
	watchTime            int
}

// AttackerStats is a public exporting type that is representing for the attackers statistics
/* Attackers (all people and robots that were entered invalid credentials) are analyzing in
 * background where it could be made one of the following decision
 * 1. attacker is not an attacker and should be removed from the list (if attackCount < watchThreshold)
 * 2. attacker could be added to the list AUTO (if attackCount >= blockThreshold with blockTill
 *    expiration) or MANUALLY (permanent block)
 */
type AttackerStats struct {
	firstAttackDetection time.Time
	lastAttackDetection  time.Time
	attackCount          int64
	archivedAttackCount  int64
	blocked              bool
	blockedAt            *time.Time
	// blockTill is Nullable , null means permanent block
	blockTill *time.Time
	// ipAddress was added for quick search in attackersIPAddresses map
	ipAddress string
	// deviceId was added for quick search in attackersDevices map
	deviceId string
}

func createAttackerList(ctx context.Context, blockTime int, watchTime int) *attackerList {
	attackers := attackerList{
		mutex:                &sync.RWMutex{},
		ctx:                  ctx,
		attackersDevices:     map[string]uuid.UUID{},
		attackersIPAddresses: map[string]uuid.UUID{},
		attackersStats:       map[uuid.UUID]AttackerStats{},
		blockTime:            blockTime,
		watchTime:            watchTime,
	}

	go attackers.processAttackers()

	return &attackers
}

// GetAttackerStats is a function for searching the stats
/* This function return AttackerStats for the selected pair (deviceId, ipAddress)
 * deviceId and ipAddress can't be used at the same time, only one of them
 * Parameters:
 *    - deviceId (is a browser fingerprint id, should be generated by a front-end), if = "",
 *      means there are no browser, API client
 *    - ipAddress - client IP, same browser could connect via proxy with different IP addresses
 * Returns pointer to attackerStats or nil
 */
func (attackers *attackerList) GetAttackerStats(deviceId string, ipAddress string) *AttackerStats {
	if deviceId == "" && ipAddress == "" {
		return nil
	}
	var id uuid.UUID
	var ok bool
	var stats AttackerStats
	attackers.mutex.RLock()
	if deviceId != "" {
		id, ok = attackers.attackersDevices[deviceId]
	}
	if !ok {
		id, ok = attackers.attackersIPAddresses[ipAddress]
	}

	if ok {
		stats = attackers.attackersStats[id]
	}
	attackers.mutex.RUnlock()
	if ok {
		return &stats
	}
	return nil
}

// UpsertDeviceStats implements statistic update for selected deviceId
/* This function perform statistic insert or update.
 * Insert creates initial values (1 attempt and so on ....)
 * Parameters:
 *    - deviceId is a browser fingerprint/identifier
 */
func (attackers *attackerList) UpsertDeviceStats(deviceId string) error {
	attackers.mutex.RLock()
	id, ok := attackers.attackersDevices[deviceId]
	attackers.mutex.RUnlock()
	return attackers.upsertStatsImpl(ok, id, false, deviceId)
}

// UpsertIpAddressStats implements statistic update for selected ipAddress
/* This function perform statistic update by replacing attackCount if stats is present
 * If there are no such stats it will be created with all fields copy to the attackerList
 * Parameters:
 *    - ipAddress is a registered attacker id
 */
func (attackers *attackerList) UpsertIpAddressStats(ipAddress string) error {
	attackers.mutex.RLock()
	id, ok := attackers.attackersIPAddresses[ipAddress]
	attackers.mutex.RUnlock()
	return attackers.upsertStatsImpl(ok, id, true, ipAddress)
}

// upsertStatsImpl implements insert or update stats data for potential attacker
func (attackers *attackerList) upsertStatsImpl(keyExists bool, id uuid.UUID, isKeyIpAddress bool, attackerSign string) error {
	attackers.mutex.Lock()
	defer attackers.mutex.Unlock()
	utcNow := time.Now().UTC()
	if keyExists {
		existingStats, statsExists := attackers.attackersStats[id]
		if statsExists {
			existingStats.attackCount++
			existingStats.lastAttackDetection = utcNow
			/* it is possible to change blocked state however it could be changed
			 * by attackCount less than threshold
			 */
			if !existingStats.blocked && attackers.checkAttackerShouldBeBlocked(&existingStats) {
				existingStats.blocked = true
				existingStats.blockedAt = &utcNow
				blockTime := utcNow.Add(time.Second * time.Duration(attackers.blockTime))
				existingStats.blockTill = &blockTime
			}
			attackers.attackersStats[id] = existingStats
		} else {
			return errors.NewAttackerStatDataNotFoundError(attackerSign, id)
		}
	} else {
		newId := uuid.New()
		stats := AttackerStats{
			firstAttackDetection: utcNow,
			lastAttackDetection:  utcNow,
			attackCount:          1,
			archivedAttackCount:  0,
			blocked:              false,
		}
		if isKeyIpAddress {
			stats.ipAddress = attackerSign
			attackers.attackersIPAddresses[attackerSign] = newId
		} else {
			stats.deviceId = attackerSign
			attackers.attackersDevices[attackerSign] = newId
		}
		attackers.attackersStats[newId] = stats
	}
	return nil
}

func (attackers *attackerList) checkAttackerShouldBeBlocked(stats *AttackerStats) bool {
	utcNow := time.Now().UTC()
	timeDelta := utcNow.Unix() - stats.firstAttackDetection.Unix()
	if timeDelta >= minTimeToCheck || stats.attackCount >= blockThreshold {
		return stats.attackCount >= blockThreshold
	}
	return false
}

// removedNonWatchingAttackers function that processed all data in maps
/* This function must be run in goroutine and do the following
 * 1. Remove after 10min attackers that didn't behave like attackers
 * 2. Check blocked till (here we should think should we unblock or should we
 *    completely remove them ?
 */
func (attackers *attackerList) removedNonWatchingAttackers() {
	attackers.mutex.RLock()
	utcNow := time.Now().UTC()
	utcNowUnix := utcNow.Unix()
	itemsToRemove := make([]AttackerStats, 0, len(attackers.attackersStats)/2)
	itemsToUnblock := make([]AttackerStats, 0, len(attackers.attackersStats)/2)
	for _, v := range attackers.attackersStats {
		// 1. Select attackers with low stats
		delta := utcNowUnix - v.lastAttackDetection.Unix()
		if !v.blocked && v.attackCount < watchThreshold && delta >= int64(attackers.watchTime) {
			itemsToRemove = append(itemsToRemove, v)
		}

		// 2. Check AUTO blocked attackers
		if v.blocked && v.blockTill != nil {
			if v.blockTill.Before(utcNow) {
				itemsToUnblock = append(itemsToUnblock, v)
			}
		}
	}
	attackers.mutex.RUnlock()

	attackers.mutex.Lock()
	for _, v := range itemsToRemove {
		var id uuid.UUID
		if v.ipAddress != "" {
			id = attackers.attackersIPAddresses[v.ipAddress]
			delete(attackers.attackersIPAddresses, v.ipAddress)
		} else {
			id = attackers.attackersDevices[v.deviceId]
			delete(attackers.attackersDevices, v.deviceId)
		}
		delete(attackers.attackersStats, id)
	}

	for _, v := range itemsToUnblock {
		var id uuid.UUID
		if v.ipAddress != "" {
			id = attackers.attackersIPAddresses[v.ipAddress]
		} else {
			id = attackers.attackersDevices[v.deviceId]
		}

		stats, ok := attackers.attackersStats[id]
		if ok {
			stats.blocked = false
			stats.archivedAttackCount += stats.attackCount
			stats.attackCount = 0
			stats.blockTill = nil

			attackers.attackersStats[id] = stats
		}
	}
	attackers.mutex.Unlock()
}

// processAttackers functions that removes attackers that we should not watch
func (attackers *attackerList) processAttackers() {
	ticker := time.NewTicker(time.Duration(attackers.watchTime) * time.Second)
	for {
		select {
		case <-attackers.ctx.Done():
			return
		case <-ticker.C:
			attackers.removedNonWatchingAttackers()
		}
	}
}

func (attackers *attackerList) setIpAddressBlockedStatus(ipAddress string, status bool) error {
	attackers.mutex.RLock()
	id, ok := attackers.attackersIPAddresses[ipAddress]
	attackers.mutex.RUnlock()
	if !ok {
		return errors.NewAttackerNotFoundError(ipAddress)
	}
	return attackers.setBlockedStatus(ipAddress, id, status)
}

func (attackers *attackerList) setDeviceIdBlockedStatus(deviceId string, status bool) error {
	attackers.mutex.RLock()
	id, ok := attackers.attackersDevices[deviceId]
	attackers.mutex.RUnlock()
	if !ok {
		return errors.NewAttackerNotFoundError(deviceId)
	}
	return attackers.setBlockedStatus(deviceId, id, status)
}

func (attackers *attackerList) setBlockedStatus(attackerSign string, attackerId uuid.UUID, status bool) error {
	attackers.mutex.Lock()
	now := time.Now().UTC()
	stats, ok := attackers.attackersStats[attackerId]
	if ok {
		// if we are blocking manually = permanent block
		stats.blocked = status
		stats.blockTill = nil
		if status {
			stats.blockedAt = &now
		}
		attackers.attackersStats[attackerId] = stats
	}
	attackers.mutex.Unlock()
	if !ok {
		return errors.NewAttackerStatDataNotFoundError(attackerSign, attackerId)
	}
	return nil
}
