package bruteforce

import (
	"github.com/google/uuid"
	"sync"
	"time"
)

type attackerList struct {
	mutex                *sync.RWMutex
	attackersIPAddresses map[string]uuid.UUID
	attackersDevices     map[string]uuid.UUID
	attackersStats       map[uuid.UUID]AttackerStats
}

// AttackerStats is a public exporting type that is representing for the attackers statistics
type AttackerStats struct {
	firstAttackDetection time.Time
	lastAttackDetection  time.Time
	attackCount          int64
	blocked              bool
	blockedAt            time.Time
	blockTill            time.Time
}

func createAttackerList() *attackerList {
	return &attackerList{
		mutex:                &sync.RWMutex{},
		attackersDevices:     map[string]uuid.UUID{},
		attackersIPAddresses: map[string]uuid.UUID{},
		attackersStats:       map[uuid.UUID]AttackerStats{},
	}
}

// GetAttackerStats is a function for searching the stats
/* This function return AttackerStats for the selected pair (deviceId, ipAddress)
 * Parameters:
 *    - deviceId (is a browser fingerprint id, should be generated by a front-end), if = "",
 *      means there are no browser, API client
 *    - ipAddress - client IP, same browser could connect via proxy with different IP addresses
 * Returns pointer to attackerStats or nil
 */
func (attackers *attackerList) getAttackerStats(deviceId string, ipAddress string) *AttackerStats {
	if deviceId == "" && ipAddress == "" {
		return nil
	}
	var id uuid.UUID
	var ok bool
	var stats AttackerStats
	attackers.mutex.RLock()
	if deviceId != "" {
		id, ok = attackers.attackersDevices[deviceId]
	}
	if !ok {
		id, ok = attackers.attackersDevices[deviceId]
	}

	if ok {
		stats = attackers.attackersStats[id]
	}
	attackers.mutex.RUnlock()
	return &stats
}

// upsertDeviceStats implements statistic update for selected deviceId
/* This function perform statistic insert or update.
 * Insert creates initial values
 */
func (attackers *attackerList) upsertDeviceStats(ipAddress string) error {
	attackers.mutex.RLock()
	id, ok := attackers.attackersIPAddresses[ipAddress]
	attackers.mutex.RUnlock()
	attackers.mutex.Lock()
	utcNow := time.Now().UTC()
	if ok {
		existingStats, statsExists := attackers.attackersStats[id]
		if statsExists {
			existingStats.attackCount++
			// todo(UMV) think about decision to block here
			existingStats.lastAttackDetection = utcNow
			attackers.attackersStats[id] = existingStats
		} else {
			// todo(UMV): provide error here
			return nil
		}
	} else {
		stats := AttackerStats{
			firstAttackDetection: utcNow,
			lastAttackDetection:  utcNow,
			attackCount:          1,
			blocked:              false,
		}
		attackers.attackersStats[id] = stats
	}
	attackers.mutex.Unlock()
	return nil
}

// upsertIpAddressStats implements statistic update for selected ipAddress
/* This function perform statistic update by replacing attackCount if stats is present
 * If there are no such stats it will be created with all fields copy to the attackerList
 */
func (attackers *attackerList) upsertIpAddressStats(ipAddress string) {

}
